# Generated by Django 3.1.6 on 2021-02-13 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CSVアフィル', max_length=50)),
                ('upload_dir', models.FileField(upload_to='csv', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
